######################################################
# Ansible Playbook to setup and configure iofog Agent
######################################################
---
- hosts: all
  remote_user: edgeworx
  port: 55501
  become: true
  vars: 
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  gather_facts: true
  tasks:
    - name: Begin!
      command: echo "Beginning install of iofogAgent software"

    - name: Hack workaround for installing non authenticated packages
      copy: content='APT::Get::AllowUnauthenticated "true";' dest=/etc/apt/apt.conf.d/99temp owner=root group=root mode=0644

    - name: Install prerequisites
      apt: name={{item}} update_cache=no
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - jq
      register: aptoutput

    - debug: var=aptoutput

    # Install iofog Agent
    - name: Download install script
      get_url: url=https://raw.githubusercontent.com/eclipse-iofog/iofog.org/saeid/jdk/static/linux.sh dest=/opt/linux.sh mode=755

    - name: Execute install script
      shell: /opt/linux.sh
      register: install

    - debug: var=install

    # Start iofog agent
    - name: Start iofog Agent
      shell: sudo service iofog-agent start

    - name: Configure Agent frequency
      shell: iofog-agent config -cf 10 -sf 10
      register: freq

    - debug: var=freq.stdout

    - name: Initializing Agent
      command: echo "Initializing Agent"

    - name: Copy wait script to Agent
      copy:
        src: scripts/wait-for-agent.sh
        dest: wait-for-agent.sh
        mode: 755
      register: copy_script

    - debug: var=copy_script

    - name: Wait for agent
      shell: ./wait-for-agent.sh
      register: wait_agent

    - debug: var=wait_agent

    - name: Change Controller URL
      shell: iofog-agent config -a http://"{{ controller_ip }}":51121/api/v3/
      register: url

    - debug: var=url

    - name: Copy setup script to Agent
      copy:
        src: scripts/init.sh
        dest: init.sh
        mode: 755
      register: copy_script

    - debug: var=copy_script

    - name: Run the Agent setup
      shell: ./init.sh http://"{{ controller_ip }}":51121/api/v3
      register: setup

    - debug: var=setup